---
title: "Ethical Considerations in Experimental Social Science Research"
author: "Discussion led by Nahomi Ichino & Alyssa René Heinze^[Slides adapted from EGAP Learning Days Online book, written by Jake Bowers, Maarten Voors, and Nahomi Ichino]"
date: '`r format(Sys.time(), "%d %B, %Y")`'
link-citations: yes
colorlinks: yes
fig_caption: yes
header-includes: |
   \setbeamertemplate{footline}{\begin{beamercolorbox}{section in head/foot}
   \hfill \insertframenumber/\inserttotalframenumber \end{beamercolorbox}}
   \usepackage{tikz}
   \usepackage{tikz-cd}
   \usepackage{textpos}
   \usepackage{booktabs,multirow,makecell}
output:
  beamer_presentation:
    keep_tex: yes
    toc: yes
    pandoc_args: [ "--toc" ]
    fig_caption: true
  revealjs::revealjs_presentation:
    center: no
    highlight: pygments
    reveal_options:
      chalkboard:
        theme: whiteboard
        toggleNotesButton: no
      previewLinks: yes
      slideNumber: yes
    reveal_plugins:
    - notes
    - search
    - chalkboard
    self_contained: no
    smart: no
    theme: default
    transition: fade
---

## What we'll do in the next hour

- A *quick* intro to ethics in human subjects (especially experimental) research: 10 min

- Small group activity: 30 min

- Final group discussion: 20 min

# Ethical considerations in your research 
## Ethical considerations

- Social science research often engages human subjects, about and from whom we collect data.

- Moreover, by its nature, experimental research is *interventionist*.  

- Field experiments seek to generate real-life impacts in society, political
  processes, and economic outcomes. That is, experimenters are humans *changing*
  the lives of other humans --- hopefully for the better, but usually without a
  direct request from those whose lives are being changed.

- We have ethical responsibilities as researchers and human beings.

## Weighing potential benefits and risks

- We must take great care to weigh the *potential benefits of the knowledge to
  be gained* and *short and long-term improvements in the lives of individuals
  and communities participating in the research* against the *potential risks
  of harm* to those individuals and communities.

- This is not so easy.

    - Whether an outcome is good or bad may depend on one's perspective, making the risk-benefit balance sometimes difficult to assess.

    - We are prone to significantly overestimating the benefits of knowledge --- so we must be cautious and have outside checks.

    - A better life for some people may imply a worse life for others.

## Considerations
    
- How would you feel if you were a research subject in your study? In the control group? In the treatment group? A relatively high-status member of the community? A relatively low-status member of the community?

- Interventions in social, political, and economic processes could change who has power, which has impacts beyond your research.

    - Example: Should avoid interventions that could change the result of close
      elections? Should researchers change such election results?

## Core tenets of research with human subjects

- Researchers must respect subjects'

    - Privacy
   
    - Autonomy
    
- Basic principles in the Belmont Report: 

    - Respect for persons
    
    - Beneficence
    
    - Justice

## Informed consent

- The **default** is that researchers should first obtain the informed consent of subjects.  This requires that subjects have the:

    - Capacity to consent to participation in the study
    
    - Freedom from coercion in deciding whether to participate
    
    - Comprehension of risks and benefits of the research
    
    - Freedom to withdraw from the study at any time

- A good general rule: Think about the consent process from the subject's perspective.

## Anonymity and confidentiality

- The **default** is anonymity (with all identifying information destroyed after the study), as it provides the most protection to subjects.

- Sometimes anonymity is not possible.  But note that researchers' promises of confidentiality to subjects can be undone by court orders.

- For example: Boston College and oral history tapes of Northern Ireland's Troubles (https://www.bbc.com/news/uk-northern-ireland-27238797).

## Power dynamics and vulnerable subjects

- Certain people --- children, prisoners, others in vulnerable positions
  without power --- may not be, or feel, able to understand the risks and
  benefits or to refuse participation.

    - But we must be aware of power dynamics more generally.  It may feel
      difficult to refuse to cooperate with donors or authority figures.

- If the study can be meaningfully conducted with a less vulnerable population, it should be.

- We require higher standards of potential benefits *to* the vulnerable populations being studied.

## Some institutional checks exist...

- An Institutional Review Board (IRB) or other Research Ethics Committee may
  review your plans for direct interactions with human subjects for data
  collection.

<!-- - Governments may have their own rules and procedures. For example, the US -->
<!--   federal government has the  [Federal Policy for the Protection of Human -->
<!--   Subjects](https://www.hhs.gov/ohrp/regulations-and-policy/regulations/common-rule/index.html). -->
<!--   Groups like the [OES](https://oes.gsa.gov) or USAID apply this rule to their -->
<!--   own research. -->

<!-- - EGAP has developing COVID-related guidelines for -->
<!--   research it supports to protect the safety of subjects, communities,  -->
<!--   enumerators, and other research staff. -->

<!-- - Universities and research institutes or organizations (like IPA) often have their own ethics review boards. -->

- In some countries, the ethics review board will be housed in a ministry of
  technology/science and be more used to dealing with medical research than
  social science research. 
  

## ... but the primary responsibility is with you

- There is no central authority that determines whether your interventions are
  ethical in a broader sense.

- It is always worth putting yourself in the shoes of your research subjects
  --- both those whom you think will gain and those whom you think will lose from
  any given intervention.

- Beyond basic human subjects protections reviewed by research ethics
  committees like IRBs, it is up to the larger community of researchers to
  develop and enforce standards.


## Designing your intervention

- Do not use interventions that we expect would harm subjects relative to what
  would happen without the intervention ("standard of care").

- Do not involve more people than necessary for the research.

- Do not make the intervention stronger than necessary for the research.

- Do not provide false information.  Avoid deception.

- Partnerships: You should report your involvement in the design of the intervention.

# Group activity
## Ethical dilemmas in experimental research

- Break into small groups (3-4 people)

- Read the vignette and instructions on the worksheet

- Discuss your responses and fill out the worksheet over the next 30 min

# Final discussion
## Group responses

- Which version of the vignette (A,B,C,D) did your group find the least permissible, and why?

- The most permissible?

- For which vignette was your visceral reaction the most different from your considered reaction, and why?

- What are the main themes that came up in your discussions on the ethical considerations of these vignettes?


