---
title: "Transparency: An Introduction"
author: "Jake Bowers --- EGAP Learning Days, Santiago de Chile"
date: today
bibliography: ../assets/learningdays-book.bib
link-citations: true
format:
  revealjs:
    embed-resources: true
    toc: true
  beamer:
    slide-level: 2
    toc: true
    colorlinks: true
    header-includes: |
      \usepackage{makecell}
      \usepackage{tikz}
      \usepackage{tikz-cd}
      \usetikzlibrary{arrows,automata,positioning,trees,babel}
      \usepackage{textpos}
      \usepackage{booktabs,multirow}
---


```{r setup, include=FALSE, echo=FALSE}
library(here)
## Shared knitr config for the Quarto decks (format-aware; loads no packages)
source("../R/qmd_setup.R")
library(DesignLibrary)
library(styler)
```

## What do we mean by "transparency" in research?

Part of the research process includes: sharing data, sharing designs, sharing
pre-analysis plans (PAPs), sharing deviations from plans.

Share with whom?

- The public
- Other researchers
- Policy makers and other decision makers (in government, in organizations, in
society)
- Political actors
- **Your future self** [@bowers2016future].


## Why transparency?

 - Makes it easier for people to interpret your results.
   - Makes it easier for you to justify your choices about: design, analysis, interpretation.
   - Helps center the debate on substance rather than methods.
 - Makes the investigator accountable to a community (or communities).
 - Makes **future you** happier with **present you** [@bowers2016future].


## How transparency?

- Share designs and pre-analysis plans on the [EGAP Registry](https://osf.io/registries/egap/discover) or [OSF](http://osf.io) or [AEA](https://www.socialscienceregistry.org/) or an easy form at [AsPredicted](https://aspredicted.org/).
- Gather the priors and hopes of a community of researchers at the [Social Science Prediction Platform](https://socialscienceprediction.org/).
 - Follow best practices for using code to change the world:
   - @bowers2016future and [10 Things To Know about Project Workflow](https://egap.org/resource/10-things-to-know-about-project-workflow/)^[see also [some of the opinionated guides about using LaTeX](https://egap.org/resource/10-things-writing-in-latex/)].
     - for example, share your code on GitHub (see [the repository for @rabb2022pnas](https://github.com/thepolicylab/COVID-VaccinesSocialNorms) or the [repository for @rabb2022nature](https://github.com/thepolicylab/COVID-SMSExperiment)).
   - See the [OES Project Process](https://oes.gsa.gov/projectprocess/) for how a **team** does transparency.
   - See the [Lab@DC OSF page](https://osf.io/wb8ue/) for examples of registrations.

---

## References
