---
title: "Transparencia: Una Introducción"
author: "Jake Bowers --- EGAP Learning Days, Santiago de Chile"
date: today
lang: es
bibliography: ../assets/learningdays-book.bib
link-citations: true
format:
  revealjs:
    embed-resources: true
    toc: true
  beamer:
    slide-level: 2
    toc: true
    colorlinks: true
    header-includes: |
      \usepackage{makecell}
      \usepackage{tikz}
      \usepackage{tikz-cd}
      \usetikzlibrary{arrows,automata,positioning,trees,babel}
      \usepackage{textpos}
      \usepackage{booktabs,multirow}
---


```{r setup, include=FALSE, echo=FALSE}
library(here)
## Shared knitr config for the Quarto decks (format-aware; loads no packages)
source("../R/qmd_setup.R")
library(DesignLibrary)
library(styler)
```

## ¿Qué queremos decir con "transparencia" en la investigación?

Parte del proceso de investigación incluye: compartir datos, compartir diseños,
compartir planes de pre-análisis (PAP), compartir desviaciones de los planes.

¿Compartir con quién?

- El público
- Otros investigadores
- Formuladores de políticas y otros tomadores de decisiones (en gobierno, en
organizaciones, en sociedad)
- Actores políticos
- **Su yo futuro** [@bowers2016future].


## ¿Por qué la transparencia?

 - Facilita que las personas interpreten sus resultados.
   - Les facilita justificar sus decisiones sobre: diseño, análisis, interpretación.
   - Ayuda a centrar el debate en el fondo y no en los métodos.
 - Hace al investigador responsable ante una comunidad (o comunidades).
 - Hace que **su yo futuro** esté más contento con **su yo actual** [@bowers2016future].


## ¿Cómo lograr la transparencia?

- Compartan diseños y planes de pre-análisis en el [Registro EGAP](https://osf.io/registries/egap/discover) o [OSF](http://osf.io) o [AEA](https://www.socialscienceregistry.org/) o un formulario fácil en [AsPredicted](https://aspredicted.org/).
- Reúnan las creencias previas ("priors") y esperanzas de una comunidad de investigadores en [Social Science Prediction Platform](https://socialscienceprediction.org/).
 - Sigan las mejores prácticas para usar el código para cambiar el mundo:
   - @bowers2016future y [10 cosas que deben saber sobre el flujo de trabajo del proyecto](https://egap.org/resource/10-things-to-know-about-project-workflow/)^[ver también [algunas de las guías con opiniones firmes sobre el uso de LaTeX](https://egap.org/resource/10-things-writing-in-latex/)].
     - por ejemplo, compartan su código en GitHub (miren [el repositorio para @rabb2022pnas](https://github.com/thepolicylab/COVID-VaccinesSocialNorms) o el [repositorio para @rabb2022nature](https://github.com/thepolicylab/COVID-SMSExperiment)).
   - Consulten el [Proceso de Proyecto OES](https://oes.gsa.gov/projectprocess/) para ver cómo un **equipo** logra transparencia.
   - Consulten la [Página de OSF del Lab@DC](https://osf.io/wb8ue/) para ejemplos de registros.

---

## Referencias


