---
title: "Quiz for Day 2 | *Quiz du jour 2*"
author: "EGAP Learning Days — Abidjan 2026"
date: today
format:
  revealjs:
    embed-resources: true
---

## Question 1 | *Question 1*

::: {.columns}
::: {.column .lang-en width="50%"}

A researcher partners with the Ministry of Agriculture and they collect data from a random sample of farmers. The survey asks two main questions. (1) Have you made use of extension services in the last year? (2) What was your yield per hectare in the last two years? The researcher finds that the yield is twice as high for those who used extension services than for those who did not. He tells the Ministry that extension services increase yields and that they should scale up the extension services to all farmers.

*Does the analysis support the researcher's recommendation?*

:::
::: {.column .lang-fr width="50%"}

Un chercheur collabore avec le Ministère de l'Agriculture pour collecter des données auprès d'un échantillon aléatoire d'agriculteurs. L'enquête pose deux questions. (1) Avez-vous fait appel à des services d'extension agricole au cours des 12 derniers mois ? (2) Quel a été votre rendement à l'hectare au cours des deux dernières années ? Le chercheur constate que le rendement est deux fois plus élevé chez ceux qui ont bénéficié de services d'extension agricole que chez ceux qui n'en ont pas bénéficié. Il indique au ministère que les services augmentent les rendements et qu'il faudrait les étendre à l'ensemble des agriculteurs.

*L'analyse soutient-elle la recommandation du chercheur ?*

:::
:::

## Question 2 | *Question 2*

::: {.columns}
::: {.column .lang-en width="50%"}

What is the fundamental problem of causal inference?

:::
::: {.column .lang-fr width="50%"}

Quel est le problème fondamental de l'inférence causale ?

:::
:::

## Question 3 | *Question 3*

::: {.columns}
::: {.column .lang-en width="50%"}

I'm conducting a study and need to send an informational email to exactly 100 participants, with the rest (the other 100) receiving a control email. The only information I have about these participants is their email addresses.

*Should I randomize using simple, complete, blocked, or clustered random assignment?*

:::
::: {.column .lang-fr width="50%"}

Je mène une étude et je dois envoyer un courriel informatif (le traitement) à exactement 100 participants, les autres recevant un courriel de contrôle. Les seules informations dont je dispose concernant les participants sont leurs adresses e-mail.

*Dois-je effectuer une assignation aléatoire simple, complète, par bloc ou par grappe ?*

:::
:::

