---
title: "Quiz for Day 3 | *Quiz du jour 3*"
author: "EGAP Learning Days — Abidjan 2026"
date: today
format:
  revealjs:
    embed-resources: true
---

## Question 1 | *Question 1* {.smaller}

|                 |                            | Treatment 1 |         |
|-----------------|----------------------------|-------------|---------|
|                 |                            | No cash     | Cash    |
| Treatment 2     | Placebo SMS                | A           | B       |
|                 | Information SMS            | C           | D       |

::: {.columns}
::: {.column .lang-en width="50%"}

I have the following factorial design. I want to know what is the effect of:

1. Getting cash and information vs neither
2. The effect of cash vs no cash
3. Among people who didn't get cash, the effect of getting the information vs not

For each one, what comparisons should I make between A, B, C, and D?

:::
::: {.column .lang-fr width="50%"}

J'ai cette conception factorielle. Je veux savoir quel est l'effet de :

1. recevoir de l'argent et des informations par rapport au fait de ne pas recevoir d'argent ou d'informations
2. recevoir de l'argent par rapport à ne pas recevoir d'argent
3. recevoir de l'information par rapport à ne pas en recevoir, parmi les personnes qui n'ont pas reçu d'argent

Pour chacune de ces questions, quelles comparaisons dois-je faire entre A, B, C et D ?

:::
:::

## Question 2 | *Question 2* {.smaller}

::: {.columns}
::: {.column .lang-en width="50%"}

Compare two experiments, one of which uses block random assignment and one of which uses cluster random assignment. Which one is which?

a. In a district with 100 villages each with 100 people in them, I randomly assign 50 people per village to treatment and 50 to control.
b. I randomly assign 100 people per village to treatment and 0 to control or 100 people per village to control and 0 to treatment.

:::
::: {.column .lang-fr width="50%"}

Comparez deux expériences aléatoires. Une utilise une assignation aléatoire par bloc et l'autre une assignation aléatoire par grappe. Identifiez la description qui correspond à la randomisation par bloc et celle qui correspond à la randomisation par grappe.

a. Dans un district composé de 100 villages comptant chacun 100 habitants, j'assigne de manière aléatoire 50 personnes par village au traitement et 50 au contrôle.
b. Au même endroit, j'assigne aléatoirement 100 personnes par village au traitement et 0 au contrôle ou 100 personnes par village au contrôle et 0 au traitement.

:::
:::

## Question 3 | *Question 3* {.compact-table}

| Design | Bias | RMSE |
|------|------|------|
| 1    | 0.1  | 0.2  |
| 2    | 0    | 0.5  |
| 3    | 0.2  | 0.2  |

::: {.columns}
::: {.column .lang-en width="50%"}

You are considering three estimators, and have figured out they have these properties. Which do you select?

:::
::: {.column .lang-fr width="50%"}

Vous envisagez 3 estimateurs. Lequel choisissez-vous ?

:::
:::

## Question 4 | *Question 4*

::: {.columns}
::: {.column .lang-en width="50%"}

What is a $p$-value?

:::
::: {.column .lang-fr width="50%"}

Qu'est-ce qu'une $p$-valeur ?

:::
:::

