---
title: 'EGAP Learning Days Research Design Form'
output:
  html_document: default
  pdf_document: default
---

+-------------------+--------------------------------------------------+
| **Section 1:      |                                                  |
| Introduction**    |                                                  |
+===================+==================================================+
| 1.  **Researcher  |                                                  |
|     name**        |                                                  |
+-------------------+--------------------------------------------------+
| 2.  **Research    |                                                  |
|     project       |                                                  |
|     title**       |                                                  |
+-------------------+--------------------------------------------------+
| 3.  **One         |                                                  |
|     sentence      |                                                  |
|     summary of    |                                                  |
|     your specific |                                                  |
|     research      |                                                  |
|     question**    |                                                  |
+-------------------+--------------------------------------------------+
| 4.  **General     | i. Why should someone who is not an academic care|
|     motivation**  | care about the results of this research? [1      |
|                   | paragraph]                                       |
|                   | ii. What policy decision(s) will your research   |
|                   | help inform? [1 paragraph]                      |
+-------------------+--------------------------------------------------+
| 5.  **Theoretical | i. What theoretical questions can this research  |
|     motivation**  | shed light on? [1 paragraph]                     |
|                   | ii. Key debate(s)/literature(s) that will be     |
|                   | informed by the answer to your research question |
|                   | [1 paragraph]                                    |
+-------------------+--------------------------------------------------+
| 6.  **Primary     | i. What are the key parameter/estimands the      |
|     hypotheses**  | research design seeks to estimate? What sign     |
|                   | and/or magnitude is predicted by primary         |
|                   | hypotheses for each parameter/estimand? [1-2     |
|                   | paragraphs]                                      |
|                   | ii. What is the logic or theory of change behind |
|                   | the primary hypotheses [1-2 paragraphs]          |
|                   | iii. What are the key pieces in the relevant     |
|                   | academic literature that inform your hypotheses? |
|                   | [2-3 pieces]                                     |
+-------------------+--------------------------------------------------+
| 7. **Secondary    | i. What are the secondary paramater/estimands the|
|    hypotheses**   | research design seeks to estimate? What sign     |
|                   | and/or magnitude is predicted by the secondary   |
|                   | hypotheses for each parameter/estimand [These may|
|                   | be conditional effects for subgroups or          |
|                   | hypotheses about additional outcomes or cross-   |
|                   | randomized treatments.]                          |
|                   | ii. What is the logic or theory of change behind |
|                   | each secondary hypothesis? [Explain what effects |
|                   | we should expect if the theory behind your       |
|                   | primary hypothesis is correct.]                  |
+-------------------+--------------------------------------------------+
| 8.  **Alternative | i. What alternative theories could explain the   |
|     explanations  | results?                                         |
|     if results are| ii. Hypothesis for an alternative outcome        |
|     consistent    | (or other subgroups) that would be consistent    |
|     with          | only with the alternative explanation and not the|
|     hypotheses**  | logic behind your primary hypothesis.            |
+-------------------+--------------------------------------------------+
| 9.  **Alternative | i. What alternative theories could explain the   |
|     explanations  | results?                                         |
|     if results are|                                                  |
|     *inconsistent*|                                                  |
|     with          |                                                  |
|     hypotheses**  |                                                  |
+-------------------+--------------------------------------------------+

+-------------------+--------------------------------------------------+
| **Section 2:      |                                                  |
| Population and    |                                                  |
| Sample**          |                                                  |
+===================+==================================================+
| 10.  **Population |                                                  |
|     of interest** |                                                  |
+-------------------+--------------------------------------------------+
| 11. **Where and   | i. Does this match up to your population of      |
|     when will your| interest, or are there conditions that make this |
|     study take    | study context different?                         |
|     place?**      |                                                  |
+-------------------+--------------------------------------------------+
| 12. **Sample      | i. How is this sample selected? Be specific about|
|     size**        | the procedure.                                   |
+-------------------+--------------------------------------------------+
| 13. **Consent**   | i. How will you obtain informed consent? If you  |
|                   | will not, what is the justification?             |
|                   | ii. Is this population vulnerable to being       |
|                   | coerced into participating in the study?         |
+-------------------+--------------------------------------------------+
| 14. **Ethics**    | i. Is the sample size large enough that you have |
|                   | sufficient power for your research conclusions to|
|                   | be credible and useful?                          |
|                   | ii. Is the sample size no larger than necessary  |
|                   | for the research?                                |
|                   | iii. Can the research (results) be used to target|
|                   | people or make people more vulnerable?           |
+-------------------+--------------------------------------------------+

+-------------------+--------------------------------------------------+
| **Section 3:      |                                                  |
| Intervention**    |                                                  |
+===================+==================================================+
| 15. **Status Quo**| i. Describe the status quo--what are the current |
|                   | conditions in terms of the outcomes you hope to  |
|                   | change? What aspects of the intervention already |
|                   | exist, if any?                                   |
+-------------------+--------------------------------------------------+
| 16.               | i. Describe your intervention(s)                 |
|   **Intervention**| ii. What is already known about the effect of the|
|                   | proposed intervention relative to the status quo?|
|                   | Is there credible evidence on the question?      |
+-------------------+--------------------------------------------------+
| 17. **Control**   | i. Describe the control condition                |
|                   | ii. Is the control condition a pure control (no  |
|                   | intervention at all) or a placebo? What is the   |
|                   | placebo contition designed to control for?       |
+-------------------+--------------------------------------------------+
| 18. **Units**     | i. To what units (level) will the intervention be|
|                   | applied? Individual, classroom, school, village, |
|                   | municipality, etc.                               |
|                   | ii. Is this the same level at which outcomes will|
|                   | be measured? If not, how will you address the    |
|                   | different levels if they do not perfectly        |
|                   | overlap?                                         |
+-------------------+--------------------------------------------------+
| 19. **Compliance**| i. What does it mean to "take" (comply with) the | 
|                   | the intervention?                                |
|                   | ii. If the intervention is a prgram, how much    |
|                   | someone need to attend (showing up once?         |
|                   | finishing the program?) in order to count as     |
|                   | having attended?                                 |
+-------------------+--------------------------------------------------+
| 20. **Non-        | i. Is there any concern with non-compliance      |
| Compliance**      | (either taking the intervention if assigned to   |
|                   | control/placebo or failing to take the           |
|                   | intervention if assigned to treatment)?          |
+-------------------+--------------------------------------------------+
| 21. **Ethics**    | i. Is the control condition no worse than the    |
|                   | status quo, according to the best evidence       |
|                   | available?                                       |
|                   | ii. Are there concerns that participants may be  |
|                   | forced to comply wiht the intervention?          |
|                   | iii. What are the risks and magnitude of         |
|                   | potentially negative effects of the treatment?   |
|                   | Are such risks concentrated on a particular      |
|                   | subset of your population?                       |
+-------------------+--------------------------------------------------+

+-------------------+--------------------------------------------------+
| **Section 4:      |                                                  |
| Outcome and       |                                                  |
| Covariates**      |                                                  |
+===================+==================================================+
| 22. **Primary     | i. What is your primary outcome?                 |
| Outcome**         |                                                  |
+-------------------+--------------------------------------------------+
| 23.               | i. How will it be measured? (Give the actual text|
| **Measurement**   | of the survey question and response options, if  |
|                   | using a survey measure. Is the outcome           |
|                   | continuous, binary, etc.?)                       |
+-------------------+--------------------------------------------------+
| 24. **Priors**    | i. What is the expected distribution of the      |
|                   | primary outcome? (This may come from a prior     |
|                   | study on a similar population or you may have to |
|                   | make an educated guess).
+-------------------+--------------------------------------------------+
| 25. **Validity    | i. Is there any concern with untruthful          |
| and measurement   | reporting? If so, how will you address it?       |
| error**           |                                                  |
+-------------------+--------------------------------------------------+
| 26. **Stages**    | i. Will you collect a baseline?                  |
|                   | ii. Will you collect a midline?                  |
|                   | iii. Will you collect multiple waves of endline  |
|                   | measurement?                                     |
|                   | iv. If you will collect a baseline or midline,   |
|                   | how will you find the same respondents (minimize |
|                   | attrition?)                                      |
+-------------------+--------------------------------------------------+
| 27. **Covariates**| i. What covariate data do you need, including for|
|                   | subgroup analysis? How will covariates be        |
|                   | measured?                                        |
|                   | ii. What addtional covariates (if any) will you  |
|                   | measure?                                         |
|                   | iii. What additional outcomes or covariates will |
|                   | you collect to distinguish between your          |
|                   | explanation and alternatives if your findings are|
|                   | consistent with your hypothesis?                 |
+-------------------+--------------------------------------------------+
| 28. **Ethics**    | i. Will data collection be onerous (time, effort)|
|                   | or painful (physically, emotionally) for any     |
|                   | respondents?                                     |
|                   | ii. Are these costs necessary? Have they been    |
|                   | minimized?                                       |
|                   | iii. Are they outweighed by the potential        |
|                   | benefits of the research to society?             |
+-------------------+--------------------------------------------------+

+-------------------+--------------------------------------------------+
| **Section 5:      |                                                  |
| Randomization**   |                                                  |
+===================+==================================================+
| 29.               | i. Complete/simple, block, cluster, factorial    |
| **Randomization   | etc.                                             |
| strategy**        |                                                  |
+-------------------+--------------------------------------------------+
| 30. **Blocks**    | i. What are they, how many blocks, how many units|
|                   | per block?                                       |
+-------------------+--------------------------------------------------+
| 31. **Clusters**  | i. What are they, how many clusters, how many    |
|                   | units per cluster?                               |
|                   | ii. If you have clusters, what is the intra-class|
|                   | correlation (ICC)?                               |
|                   | iii. Is clustering strictly necessary, or could  |
|                   | you randomize at the individual level?           |
+-------------------+--------------------------------------------------+


+-------------------+--------------------------------------------------+
| **Section 6:      |                                                  |
| Analysis**        |                                                  |
+===================+==================================================+
| 32.               | i. What is your estimator?                       |
| **Estimator**     |                                                  |
+-------------------+--------------------------------------------------+
| 33. **Standard    | i. What kind of standard errors will you use?    |
| Errors**          |                                                  |
+-------------------+--------------------------------------------------+
| 34. **Test**      | i. If you plan to report a p-value, what kind of |
|                   | test will you use?                               |
+-------------------+--------------------------------------------------+
| 35. **Missing     | i. How will you handle missing data?             |
| Data**            |                                                  |
+-------------------+--------------------------------------------------+
| 36. **Effect      | i. What is the expected effect size? What is the |
|     size**        | minimum effect size that would make the study    |
|                   | worth running? what effect sizes have similar    |
|                   | studies found?                                   |
+-------------------+--------------------------------------------------+
| 37. **What is your|                                                  |
| power?**          |                                                  |
+-------------------+--------------------------------------------------+

+-------------------+--------------------------------------------------+
| **Section 7:      |                                                  |
| Implementation**  |                                                  |
+===================+==================================================+
| 38.               | i. How will you conduct the randomization? (on a |
| **Randomization** | computer in advance, drawing from an urn in      |
|                   | public, etc.)                                    |
+-------------------+--------------------------------------------------+
| 39.               | i. Who will implement the intervention?          |                
| **Implementation**| ii. Are there any dangers to your research team, |
|                   | including enumerators? How will you minimize     |
|                   | them?                                            |
|                   | iii. How will you track the quality of the       |
|                   | implementation of the intervention?              |
+-------------------+--------------------------------------------------+
| 40. **Compliance**| i. Who will measure compliance?                  |
+-------------------+--------------------------------------------------+
| 41. **Data        | i. How will you manage the data? (security,      |
| management**      | anonymity, etc.)                                 |
+-------------------+--------------------------------------------------+