---
title: "Formulaire de design de recherche"
format:
  html:
    toc: false
    theme: default
    page-layout: full
    embed-resources: true
format-links: false
---

### Description générale

|                              |                                                                                   |
|:-----------------------------|:----------------------------------------------------------------------------------|
| 1. **Nom du groupe**         |                                                                                   |
| 2. **Question de recherche** | Quelle est votre question de recherche ?                                          |
| 3. **Intervention**          | Décrivez l'intervention que vous prévoyez de mener.                               |
| 4. **Contrôle**              | Décrivez ce que fera ou recevra le groupe contrôle, le cas échéant.              |
| 5. **Unité d'analyse**       | À quel niveau l'intervention sera-t-elle menée ? Par exemple, sur des individus ? Par des groupes ? |
| 6. **Éthique**               | Considérez les implications éthiques de votre expérience. Y a-t-il des risques ou des bénéfices potentiels pour les participants ? |

### M — Modèle

|                              |                                                                                   |
|:-----------------------------|:----------------------------------------------------------------------------------|
| 7. **N**                     | Combien d'unités aurez-vous ?                                                     |
| 8. **Hypothèse principale**  | Quel effet du traitement hypothétisez-vous ?                                      |

### I — Interrogation

|                              |                                                                                   |
|:-----------------------------|:----------------------------------------------------------------------------------|
| 9. **Paramètre**             | Décrivez votre question précisément en termes de traitement, de résultat et de toute autre caractéristique pertinente de votre population. Par exemple, nous nous intéressons à l'effet moyen du traitement de X sur Y (ATE). Ou nous nous intéressons à la différence de l'effet de X sur Y pour les hommes et pour les femmes (une différence de CATE). |

### D — Données

|                              |                                                                                   |
|:-----------------------------|:----------------------------------------------------------------------------------|
| 10. **Randomisation**        | Quelle randomisation utiliserez-vous : simple, complète, par grappe, par bloc, factorielle, etc. ? |
| 11. **Résultat principal**   | Comment mesurerez-vous votre résultat principal ?                                 |

### A — Analyse

|                              |                                                                                   |
|:-----------------------------|:----------------------------------------------------------------------------------|
| 12. **Estimateur**           | Quel estimateur utiliserez-vous (différence des moyennes, régression, régression avec effets fixes par bloc et pondération inverse de la probabilité, etc.) ? |
| 13. **Erreur-type**          | Quel type d'erreurs-types utiliserez-vous ?                                       |

## Diagnostic

|                              |                                                                                   |
|:-----------------------------|:----------------------------------------------------------------------------------|
| 14. **Biais**                | Vous attendez-vous à ce que votre estimateur soit non biaisé ? Pourquoi ?           |
| 15. **Puissance statistique**| Quelle est la puissance statistique de votre design ?                             |
