---
title: "Research design form"
format: html
---

### General description

|                           |                                                                                   |
|:--------------------------|:----------------------------------------------------------------------------------|
| 1. **Name of the group**  |                                                                                   |
| 2. **Research question**  | What is your research question?                                                   |
| 3. **Intervention**       | Describe the intervention you plan to run.                                        |
| 4. **Control**            | Describe what the control group will do or receive, if anything.                  |
| 5. **Unit of analysis**   | At what level will the intervention be run? For example, on individuals? By groups? |
| 6. **Ethics**             | Consider the ethical implications of your experiment. Are there any potential harms or benefits to participants? |

### M — Model

|                           |                                                                                   |
|:--------------------------|:----------------------------------------------------------------------------------|
| 7. **N**                  | How many units will you have?                                                     |
| 8. **Main hypothesis**    | What do you hypothesize for the effect of the treatment?                          |

### I — Inquiry

|                           |                                                                                   |
|:--------------------------|:----------------------------------------------------------------------------------|
| 9. **Estimand**           | Describe your question precisely in terms of the treatment, outcome, and any other relevant features of your population. For example, we are interested in the average treatment effect of X on Y (ATE). Or we are interested in the difference of the effect of X on Y for men and for women (a difference in CATEs). |

### D — Data strategy

|                           |                                                                                   |
|:--------------------------|:----------------------------------------------------------------------------------|
| 10. **Randomization**     | What randomization will you use: simple, complete, cluster, block, factorial, etc.? |
| 11. **Main outcome**      | How will you measure your main outcome?                                           |

### A — Answer strategy

|                           |                                                                                   |
|:--------------------------|:----------------------------------------------------------------------------------|
| 12. **Estimator**         | What estimator will you use (difference in means, regression, regression with block fixed effects and inverse probability weighting, etc.)? |
| 13. **Standard error**    | What type of standard errors will you use?                                        |

## Diagnosis

|                           |                                                                                   |
|:--------------------------|:----------------------------------------------------------------------------------|
| 14. **Bias**              | Do you expect your estimator to be unbiased? Why?                                 |
| 15. **Statistical power** | What is the statistical power of your design?                                     |
