---
title: "20 Stages of an experimental project | *20 Étapes d'un projet expérimental*"
author: "Macartan Humphreys"
date: today
bibliography: assets/learningdays-book.bib
format:
  revealjs:
    embed-resources: true
---


## Experimentation: Stages (1) | *Expérimentation : étapes (1)* {.smaller}

::: {.columns}
::: {.column .lang-en width="50%"}

1. Find a good **question**: Minimally, find an $X$ and a $Y$. You might have  $X$-based motivations, $Y$-based motivations, Theory based, hypothesis based, mechanism based, replication focused
2. Survey literatures, identify **contribution**.
3. Identify funders and partners, **resources**. Perhaps run exploratory pilot analyses.
4. Develop a **design**: Data strategy | Measurement strategy | Answer strategy
5. **Simulate** the design: Power analysis, confirmation of properties of estimators
6. **Present**! Gather feedback
7. Gather **priors**: what do others expect will happen?
8. Apply for **ethics** approval
9. Ensure **compliance** with other provisions (e.g. GDPR)!
10. **Register** a pre-analysis plan (e.g. OSF, AEA)

:::
::: {.column .lang-fr width="50%"}

1. Trouver une bonne **question** : au minimum, identifier un $X$ et un $Y$:  motivations liées au $X$, motivations liées au $Y$, théorie, hypothèses, mécanismes, réplication
2. Passer en revue la littérature, identifier la **contribution**.
3. Identifier bailleurs de fonds et partenaires, **ressources**. Peut-être mener des analyses pilotes exploratoires.
4. Élaborer un **design** : stratégie de données | stratégie de mesure | stratégie de réponse
5. **Simuler** le design : analyse de puissance, propriétés des estimateurs
6. **Présenter** ! Recueillir des retours
7. Recueillir des **priors** : que s'attendent les autres ?
8. Demander l'approbation **éthique**
9. Assurer la **conformité** aux autres exigences (p. ex. RGPD) !
10. **Enregistrer** un plan de pré-analyse (p. ex. OSF, AEA)

:::
:::

## Experimentation: Stages (2) | *Expérimentation : étapes (2)* {.smaller}

::: {.columns}
::: {.column .lang-en width="50%"}

11. Conduct **Baseline** (if needed): **With live data quality control!**
12. Implement **randomization**
13. Gather **process** observations
14. Implement **Endline**. **With live data quality control!**
15. Run **analysis**; check analysis
16. Generate **key tables**
17. **Present** to colleagues, but also present to any stakeholders
18. Prep **replication** materials. Make **data** and code available to others
19. **Writeup**
20. **Submit** [Get rejected — Submit again]

:::
::: {.column .lang-fr width="50%"}

11. Mener le **baseline** (si nécessaire) : **contrôle qualité des données en direct !**
12. Mettre en œuvre la **randomisation**
13. Recueillir des observations de **processus**
14. Mener l'**endline**. **Contrôle qualité des données en direct !**
15. Exécuter l'**analyse** ; vérifier l'analyse
16. Produire les **tableaux clés**
17. **Présenter** aux collègues et aux parties prenantes
18. Préparer les matériaux de **réplication**. Rendre **données** et code disponibles
19. **Rédaction**
20. **Soumettre** [Rejet — soumettre à nouveau]

:::
:::

