---
title: "Get ready to work on projects | *Préparez-vous à travailler sur les projets*"
author: "Adikath + Vincent"
date: today
bibliography: learningdays-book.bib
format: 
  revealjs:
    embed-resources: true

---

## Our plan | *Notre plan*

::: {.columns}
::: {.column .lang-en width="50%"}

- We will break up into 6 teams of 3–4 people
- Over the rest of the week you will *design*, *implement*, *analyze*, and *present* an experiment

:::
::: {.column .lang-fr width="50%"}

- Nous formerons 6 équipes de 3 à 4 personnes
- Pendant le reste de la semaine, vous allez *concevoir*, *mettre en œuvre*, *analyser* et *présenter* une expérience

:::
:::

## First steps | *Premières étapes*

::: {.columns}
::: {.column .lang-en width="50%"}

- Come up with a question and a treatment: find an $X$ and a $Y$. The $X$ is something that you have to be able to randomly vary; the $Y$ is the outcome you care about
- Figure out a data strategy: how will you implement the intervention, how will you measure outcomes?
- Figure out an answer strategy: what analysis will you do? How will you report results?

:::
::: {.column .lang-fr width="50%"}

- Formulez une question et un traitement : identifiez un $X$ et un $Y$. Le $X$ est quelque chose que vous devez pouvoir varier aléatoirement ; le $Y$ est le résultat qui vous intéresse
- Définissez une stratégie de données : comment allez-vous mettre en œuvre l'intervention, comment allez-vous mesurer les résultats ?
- Définissez une stratégie d'analyse : quelle analyse allez-vous faire ? Comment allez-vous présenter les résultats ?

:::
:::

## Second steps | *Étapes suivantes*

::: {.columns}
::: {.column .lang-en width="50%"}

- Summarize these design elements in terms of MIDA
- Complete the design form
- If you want to try to declare a design formally, talk with us

:::
::: {.column .lang-fr width="50%"}

- Résumez ces éléments de design en termes de MIDA
- Complétez le formulaire de design
- Si vous voulez essayer de déclarer un design formellement, parlez-en avec nous

:::
:::

## What kind of intervention can you reasonably do in such a short period? | *Quel type d'intervention peut-on raisonnablement mener en si peu de temps ?*

::: {.columns}
::: {.column .lang-en width="50%"}

Actually, lots. Let's think together through a set of possibilities:

1. Effect of coffee on attention
2. Effect of breaks
3. Effect of taking part in a group discussion on understanding a topic
4. Effect of providing some information on something
5. Effect of spending time with someone from a different language group

:::
::: {.column .lang-fr width="50%"}

En fait, beaucoup. Réfléchissons ensemble à un ensemble de possibilités :

1. Effet du café sur l'attention
2. Effet des pauses
3. Effet de participer à une discussion de groupe sur la compréhension d'un sujet
4. Effet de fournir une information sur quelque chose
5. Effet de passer du temps avec quelqu'un d'un autre groupe linguistique

:::
:::

## Let's go | *C'est parti*
